### ISSUE TITLE
Workaround for tokens with impossible states? ("problem found for token X" error)

### ISSUE THREAD

**Issue by alfredomg** [NorskRegnesentral/skweak#10]
Hi,

First of all I would like to congratulate you on launching skweak. It's a much needed tool for us who need weak supervision for structured prediction problems like NER. 

While trying out skweak, I hit the "problem found for token X" error. I had a review of the `fit` method and this happens when a token ends up with an impossible state (i.e. a logprob of -inf):

```
# Make sure there is no token with no possible states

if (np.isnan(framelogprob).any() or  # type: ignore
    framelogprob.max(axis=1).min() < -100000):
pos = framelogprob.max(axis=1).argmin()
print("problem found for token", doc[pos], "in", self.name)
return
```

Not sure if there should be some sort of handling for this token rather than just returning from `fit` without any value? 

As a workaround I modified this line in `_compute_log_likelihood` from this:

```
logsum = np.where(X_all_obs, logsum, -np.inf)
```

to this:

```
logsum = np.where(X_all_obs, logsum, -100000.0)
```

I.e. I'm changing an impossible probability to an "almost" impossible probability. The HMM model happily finished training and I was able to get meaningful predictions from it. However, I'm not sure if my workaround is doing more harm than good. Ideally, I think there should be some sort of handling for such a token with an impossible state.

Thanks a lot in advance. And I would like to thank you again for putting together this very much needed and easy to use weak supervision library.

Thanks,
Alfredo

**Comment by plison** [comment]
Hi Alfredo,
Thanks (and sorry for the late answer)! 

Yes, you're perfectly right, once could certainly replace the negative infinity by a large negative number, and it's something we had actually tested in a previous version. However, we decided to go for the current solution for two reasons:
- the first reason is computational, since alternatives with a zero probability can be directly skipped, which can speed up inference by reducing the number of alternatives to consider ;
- the second reason relates to debugging: typically, if one reaches a state where no possible state value has a likelihood > 0, this signals a serious problem that should be fixed ASAP, as it is likely to create many other convergence problems down the line. It's something that happened to us quite a few times when testing various labelling functions, and we found it quite useful to get a clear error message thrown when that happens.

This being said, it's true that the current is quite cryptic, and we should do a better job at providing more informative cues about what's happening and what should be fixed.
