### ISSUE TITLE
Heuristic function that specifically says a span is NOT an entity?

### ISSUE THREAD

**Issue by alfredomg** [NorskRegnesentral/skweak#12]
Hello,

Is there a way to write a heuristic function that specifically indicates that a span should not be interpreted as an entity? I.e. that it should be treated with an "O" label? Basically, I'd like to have a function that actively votes that span is NOT an entity, rather than abstaining on it.

**Comment by michelleful** [comment]
+1, exactly the same question :)

**Comment by plison** [comment]
Sorry for the answering delay! But I think I have a relatively simple solution to your problem: the easiest is to create a normal heuristic function (like with `FunctionAnnotator`), and have it output a special label such as `NOT_A_LABEL` . Then, when aggregating all the labels with the `HMM` or the `MajorityVoter`, specify that `NOT_A_LABEL` is an underspecified label of `O`:

```
hmm = skweak.aggregation.HMM("hmm", ["PERSON", "DATE", "MONEY"])
hmm.add_underspecified_label("NOT_A_LABEL", ["O"])
```

This way, the aggregation will know that your labelling function has produced a signal that is equivalent to "O" -- but since the label is defined as an underspecified label (and not a "concrete" label), it will also know that NOT_A_LABEL is not a "real" label.

I've had to make some minor changes to the code to make it working,  let me know whether this works!

**Comment by alfredomg** [comment]
Thanks for the reply! I'll try it out and let you know! Thanks!
