### ISSUE TITLE
Consider using custom attribute extension instead of doc.spans

### ISSUE THREAD

**Issue by kabirkhan** [NorskRegnesentral/skweak#4]
I love the idea of this project and I'm definitely planning to utilize it in future work. One point of discussion is it's a little confusing for a spaCy user to have `doc.spans` be a dict with the spans for each labeling function. 

I think it might be a little easier if these were contained in a custom extension so you could access these annotations as something like `doc._.skweak_spans` and the doc.spans attribute was only set post aggregation.

If there's a rationale I'm missing, no big deal.

Thanks!

**Comment by kabirkhan** [comment]
nvm just saw this is a new spacy v3 feature!

**Comment by plison** [comment]
Thanks for your interest in the toolkit ! Yes, it's indeed a new feature introduced in the new version of SpaCy. We had actually also considered using custom extensions, but it turned out to be quite cumbersome to use (especially when it comes to preserving annotations after storing documents to disk).  This new `SpanGroup` turned out to be quite convenient to use.
