### ISSUE TITLE
skweak.utils.display_entities behavior in Jupyter notebooks

### ISSUE THREAD

**Issue by wpnbos** [NorskRegnesentral/skweak#5]
Windows 10
Python 3.8.3

Hi, 

It would seem that the skweak.utils.display_entities() function with the "hmm" parameter has some undesired behavior in Jupyter notebooks. Rather than displaying the entities like it would with the "spacy" parameter, which looks like this: 

<img width="436" alt="Screenshot 2021-04-29 113309" src="https://user-images.githubusercontent.com/33165624/116530863-cd917480-a8de-11eb-8dc5-47ce229174ea.png">

Where lines are printed to fit the screen, and entities are in a box with their label, the "hmm" parameter gives this result: 

<img width="256" alt="Screenshot 2021-04-29 113328" src="https://user-images.githubusercontent.com/33165624/116530952-e863e900-a8de-11eb-9a70-797e2177710a.png">

With lines being displayed awkwardly, and entity labels masking the actual word that was tagged (the COMPANY tag shows, but the entity "Reuters" is not visible). 

These pictures are taken from a top-to-bottom run, unaltered quick_start.ipynb as found in the examples directory. 

Love the package by the way!

**Comment by plison** [comment]
Yes you're perfectly right, I had only tested this behaviour in Jupyter Lab, but not older Jupyter Notebooks. We had implemented a functionality that relies on HTML tooltips to interactively visualise the prediction of each labelling function for a given token. But it turns out HTML tooltips are only supported in Jupyter Lab.

So I've turned the use of tooltips off by default. But if you wish to display those tooltips, I'd recommend to switch to Jupyter Lab (which, in my opinion, is a big improvement compared to Jupyter Notebook), and set the flag `add_tooltip=True`.
