### ISSUE TITLE
MUC-6 dataset

### ISSUE THREAD

**Issue by agosiewska** [NorskRegnesentral/skweak#6]
Hello, I really appreciate your work on weak supervision.
I have noticed that in your preprint, you show the results of skweak on the MUC-6 corpus.
https://arxiv.org/abs/2104.09683

I am testing different generative models and I would like to compare them on the same data sets, however, I cannot find MUC-6. 
Could you, please provide me a source from which you downloaded the data set? 
Is it somewhere behind a paywall?

**Comment by plison** [comment]
Hi! The MUC-6 data file is too big to be put directly in the repository (due to Github's file size constraints), so we put it in the "assets" of the release: https://github.com/NorskRegnesentral/skweak/releases/download/0.2.8/muc6.spacy
This file is in the Spacy `DocBin` format. Note the documents are for some reason duplicated, but it doesn't change anything to the results of course.

**Comment by agosiewska** [comment]
Thank you very much!
